### ISSUE TITLE
_handleFrame slow

### ISSUE THREAD

**Issue by frankvolkel** [skaarj1989/mWebSockets#10]
I am yet to thoroughly diagnose the issue, but preliminary findings suggest that _handleFrame, which is invoked via client.listen() in loop() is blocking and slow. 

My application, which is running on a Arduino Mega 2560 R3 with a W5100 Ethernet Shield requires high levels of responsiveness.

**Comment by skaarj1989** [comment]
@frankvolkel 

What do you mean by saying "slow" and "high levels of responisveness"
Also don't expect much from 8bit microcontroller
