### ISSUE TITLE
w5500 and esp32 websocket server

### ISSUE THREAD

**Issue by MaxESP** [skaarj1989/mWebSockets#14]
dear sir,

I was generic esp32 working with ethernet.h ans spi config

i want to implement websocket server to w5500 with esp32

do you have some idear?

thank a lot

**Comment by skaarj1989** [comment]
Hi, sorry for so late reply.
> i want to implement websocket server to w5500 with esp32

It depends if ESP32 supports W5500.

Unfortunately I don't have any ESP32

**Comment by k-zhai** [comment]
I'm also interested in knowing if this works for ESP32

**Comment by MaxESP** [comment]
For the moment a made w5500 workable just simple http server on esp32. As I am a profesionnal in home automation websocket is very good technology . 
I explain as now all smartphone are very powerfull the fact that you put all html js and css on the phone is easy , than you just have to communicate to the server by websocket to receive command 
make the home automation very fast responsive.   I am have a problem with IOS to implement websocketweb view

**Comment by skaarj1989** [comment]
I've received **ESPDUINO-32** and tested it - works fine.

You have to comment ``virtual void begin(uint16_t port=0) =0;`` in **Server.h** located in:
`C:\Users\{your-user-name}\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\cores\esp32`

And during initialization (it may vary for your board):
``Ethernet.init(5);``

**Comment by MaxESP** [comment]
I going to try thank a lot
