### ISSUE TITLE
webSocket : bug with firefox 7.1 client and arduino server

### ISSUE THREAD

**Issue by jmih** [skaarj1989/mWebSockets#15]
Following a bug `UPGRADE_REQUIRED` encountered with firefox 7.1 on the client side and arduino on the server side, I noticed that the "Connection" header was different from the other web browsers. 
Firefox : Connection: keep-alive, Upgrade
others : Connection: Upgrade
To fix this problem, I modified line 255 of the WebSocketServer.cpp file this way: 
`if ((strcmp_P(value, (PGM_P)F("Upgrade")) != 0) && (strcmp_P(value, (PGM_P)F("keep-alive,")) != 0))`
There is probably a more elegant and general correction to this bug.

**Comment by skaarj1989** [comment]
@jmih 
Fixed. Simple "includes" check for **Upgrade** in **Connection** header instead of strict **Upgrade** value
