### ISSUE TITLE
Base64 library

### ISSUE THREAD

**Issue by gitneko** [skaarj1989/mWebSockets#21]
Currently I'm looking into this library for a project of mine (part of #19) and I've noticed that this library requires a base64 implementation, but none of the ones I've been looking at in the Arduino Library Manager actually define the needed functions.

Which library do you need installed to have these base64 functions around? Would you be willed to migrate to a different library, if the library can not be found in the library manager?

Currently I have the following one installed: <https://github.com/agdl/Base64>

And the following two seem sane from a quick view:
- <https://github.com/Densaugeo/base64_arduino>
- <https://github.com/dojyorin/arduino_base64>

**Comment by skaarj1989** [comment]
It's bundled.

**Comment by gitneko** [comment]
Ah, yes it's bundled with git, but not in the latest version. Therefore this was getting overlooked by me and the compiler... :) 

Can I assume you will make a new release once this library works fine on SAMD (after my feedback)?

**Comment by skaarj1989** [comment]
both **base64** and **CryptoLegacy** are bundled in newest release.
