### ISSUE TITLE
error 1006

### ISSUE THREAD

**Issue by gfduck** [skaarj1989/mWebSockets#27]
I use example of simple client websocket, in localhost works correctly  but in my hosting appear error 1006.
The Arduino connect and desconnect after 1 second in Server.

Can you help me?

This is my code:

```cpp
#include <WebSocketClient.h>
using namespace net;

byte mac[]{ 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
# define _SERIAL Serial

WebSocketClient client;

void setup() {
  _SERIAL.begin(9600);
  Ethernet.begin(mac); //, ip);

  _SERIAL.print(F("Device IP: "));
  _SERIAL.println(Ethernet.localIP());

  client.onOpen([](WebSocket &ws) {
    _SERIAL.println(F("Connected"));

    constexpr char message[]{ "Hello from Arduino client!" };
    ws.send(WebSocket::DataType::TEXT, message, strlen(message));
  });

  client.onMessage([](WebSocket &ws, const WebSocket::DataType &dataType,
                     const char *message, uint16_t length) {
    switch (dataType) {
    case WebSocket::DataType::TEXT:
      _SERIAL.println(F("Received text message"));
      _SERIAL.println(message);
      break;
    case WebSocket::DataType::BINARY:
      _SERIAL.println(F("Received binary data"));
      break;
    }

    ws.send(dataType, message, length); // echo back to server
  });

  client.onClose(
    [](WebSocket &ws, const WebSocket::CloseCode &code, const char *reason,
      uint16_t length) { _SERIAL.println(F("Disconnected")); });

  if (!client.open("server.com", 80, "/chat")) {
    _SERIAL.println(F("Connection failed!"));
    while (true)
      ;
  }
}

void loop() { client.listen(); }
```

![1006](https://user-images.githubusercontent.com/66056030/104969614-bf6eb680-59c7-11eb-8b67-dfeaf6ab4b31.png)

**Comment by skaarj1989** [comment]
Hi @gfduck 
Could you post arduino log?

**Comment by gfduck** [comment]
Thanks for answer!

This is a log from Arduino. I use W5100 ethernet.

In localhost works ok but in hosting not work.



![logarduino](https://user-images.githubusercontent.com/66056030/105082624-9fe09800-5a72-11eb-868e-1f1d7708b9ed.png)

**Comment by skaarj1989** [comment]
Is your server *ws* or *wss*?
Please enable debug macros in `config.h`

**Comment by gfduck** [comment]
Thanks for answer!.

This is file config.h, how to enable enable debug macros?

Can you send the correct content of file?

Thanks!

#pragma once

/** @file */

/**
 * @def _DEBUG Enables __debugOutput function.
 * @def _DUMP_HANDSHAKE Prints any handshake request/response on Serial output.
 * @def _DUMP_HEADER Prints frame header on Serial output.
 * @def _DUMP_FRAME_DATA Prints frame data on Serial output.
*/

/**
 * @def NETWORK_CONTROLLER
 * @brief Specifies network controller, available values:
 *  - ETHERNET_CONTROLLER_W5X00
 *  - ETHERNET_CONTROLLER_ENC28J60
 *  - NETWORK_CONTROLLER_WIFI
 */

//#define _DEBUG
//#define _DUMP_HANDSHAKE
//#define _DUMP_HEADER
//#define _DUMP_FRAME_DATA

#define NETWORK_CONTROLLER ETHERNET_CONTROLLER_W5X00

/** Maximum size of data buffer - frame payload (in bytes). */
constexpr uint16_t kBufferMaxSize{ 256 };
/** Maximum time to wait for endpoint response (in milliseconds). */
constexpr uint16_t kTimeoutInterval{ 5000 };

**Comment by gfduck** [comment]
My server is ws

**Comment by skaarj1989** [comment]
Just uncomment these four defines. Are you trying to connect by passing ip address or http://?

**Comment by gfduck** [comment]
I try to connect with url.

This is a log debug:
![logarduino2](https://user-images.githubusercontent.com/66056030/105095817-f2c34b00-5a84-11eb-844b-2154a8817846.png)

**Comment by skaarj1989** [comment]
Ok, now it's clear.
Go into `WebSocketClient.cpp` and replace `strcmp_P` with `strcasecmp_P` in the line 172.

**Comment by gfduck** [comment]
ohhh it`s awesome!!

it`s working now!!

Thanks a lot!.

Other problem,  In few time to connect arduino is disconnect. 
This is a log.

I  attach screenshot.
![logarduino3](https://user-images.githubusercontent.com/66056030/105097681-c5c46780-5a87-11eb-9f14-ff183df9c6b5.png)

**Comment by gfduck** [comment]
In webserver is error 1002

**Comment by skaarj1989** [comment]
Any debug message?

**Comment by gfduck** [comment]
During this days I will do some test on the library and I will let you know! I am so thankful for your help

**Comment by skaarj1989** [comment]
You're welcome.
