### ISSUE TITLE
Automatically reconnect over WS on ethernet disconnect

### ISSUE THREAD

**Issue by ivanjermakov** [skaarj1989/mWebSockets#34]
Trying to figure out how to reconnect to WS, when ethernet connection goes down (physical disconnect, server restart, etc.)

**Comment by skaarj1989** [comment]
HI @ivanjermakov,
You could reconnect in `onClose` callback, I used something similar [here](https://github.com/skaarj1989/mWebSockets/blob/a0407157dd18dc9f966f7fef6d48804d84acb872/autobahn-testsuite/test/fuzzingclient/fuzzingclient.ino#L251)
