### ISSUE TITLE
MKR1000 and socket.io

### ISSUE THREAD

**Issue by Josua2012** [skaarj1989/mWebSockets#35]
Hello,

Can your library be used to communicate with a server created with nodejs + express + socket.io?
Can it be used with a MKR1000 and Wifi101? 
Do you have examples using Wifi101? 

Thank you very much for all your information. 

Regards,

**Comment by skaarj1989** [comment]
Hi @Josua2012 
1. `mWebSockets` does not support `socket.io` and I don't plan to implement it anytime soon. (you could use `ws` instead though).
2. `Arduino MKR1000` is built on the `SAMD21`, which is currently being supported.
3. In theory, `Wifi101` could work. Unfortunately, I don't have any `Wifi101` module at the moment, so I can't test it.
