### ISSUE TITLE
WSS connection

### ISSUE THREAD

**Issue by andrettaadriano1** [skaarj1989/mWebSockets#42]
Hello, your library is amazing!
I use it with an internet sheild w5500 and an arduino mega and it goes great

My problem:
I haven't found a way to connect to websocket via ssl
for example I would like to connect to:
wss: //echo.websocket.org
how can I do?

thank you

**Comment by skaarj1989** [comment]
Hi @andrettaadriano1 

You need **TLS**. Unfortunately, the **AVR** family is not capable of doing that (as far as I know).

**Comment by andrettaadriano1** [comment]
which microcontroller do you recommend to use with its library to connect to a wss server?

**Comment by skaarj1989** [comment]
**ESP8266** or **ESP32**
Be advised that I have never tasted this library with secured WebSocket.
