### ISSUE TITLE
note: array types have different bounds

### ISSUE THREAD

**Issue by guilhermeaiolfi** [skaarj1989/mWebSockets#51]
**Describe the bug**
Hi, I am trying to use this library but I am getting the following message after compiling:
```
WebSocketServer.h:14:7: note: array types have different bounds
 class WebSocketServer {
       ^
```

**Environment info**
- IDE 1.8.16
- Arduino Uno
- WiFi
- mWebSockets 1.4.0

Should I be worried about it?

**Comment by skaarj1989** [comment]
@guilhermeaiolfi It's fine. You can also use **master** version (I think it's time to create a new release).

**Comment by guilhermeaiolfi** [comment]
That would be nice. I'm just started playing with arduíno (yesterday was the first day) and I am using the library manager. I guess I could manually use the master code but I have a lot to figure it out yet. BTW, thank you for this library, it is exactly what I wanted it.
