### ISSUE TITLE
Using SSL for Server

### ISSUE THREAD

**Issue by dandreossi** [skaarj1989/mWebSockets#52]
I can't make it work with Chrome while with Firefox is ok.
The reason is because the WebSocket Server is insecure.
It is possible to implement SSL to the Library?

- IDE w/version [Visual Studio Code with platoformio]
- Platform/Board: [ Arduino Mega 2560 ]
- Network controller (shield or module): [EthernetShield w5100]

**Comment by skaarj1989** [comment]
Unfortunately it's impossible. See #42 and #46
