### ISSUE TITLE
WiFiEsp(AT) support

### ISSUE THREAD

**Issue by guilhermeaiolfi** [skaarj1989/mWebSockets#54]
Hi,

I just want to start the discussion about using your library with WiFiEspAT. I think that's the simplest way of using it for new fellows in the arduino world like me. None of the websocket libraries have compatibility with WiFiEsp or WiFiEspAT, I think that would be a big plus.

After somedays of learning arduino/C/mWebSocket /WiFiEspAT I was able to make it work. So it is definitely possible. The problem is that it is very unstable and it doesn't seems to be related to the communication with the ESP8266.

Depending on where and how many printf() I had in the code, the behavior changed. And it is always in the mWebSocket side. In one of those case in the WebSocket.cpp code:

```c
if (header.length + offset >= kBufferMaxSize)
      return close(CloseCode::MESSAGE_TOO_BIG, true);
```
That was returning true for header.length = 5, offset = 0 and kBufferMaxSize = 256. Sometimes the arduino was simply halting in the middle of the code. But like I said, sometimes it works. I don't have any other board to test, but every other sketch works fine and consistently.

Anyhow, an interface with AT commands is something that you would be willing to support and do you have any idea what would be cause of those random behaviors?

**Comment by skaarj1989** [comment]
@guilhermeaiolfi
Looks like **WiFiEspAT** requires AT firmware version >= 1.7 so I tried to upgrade my **ESP-01** module to 2.2.1.0 using **ESP8266 Flash Downloader**, unfortunately it fails at 96%, (burning the stock one succeeded).

Where did you get firmware? And which flasher do you use?
