### ISSUE TITLE
Event onPing on the client

### ISSUE THREAD

**Issue by E3ton** [skaarj1989/mWebSockets#60]
Сould you add an event listener onPing on the client?

client.onPing([](WebSocket &ws) {...

**Comment by skaarj1989** [comment]
Yes, I can do that.
Out of curiosity, what do you need that for? is it urgent?

**Comment by E3ton** [comment]
It is needed for a workaround of https://github.com/skaarj1989/mWebSockets/issues/50
My server is regularly pinging the socket, and I want to save the last ping's timestamp so there is a way to tell if server is alive or not.

**Comment by skaarj1989** [comment]
I've just pushed the feature to `master` branch

Here's how to use it:

```cpp
client.onPing([](WebSocket &ws, const char *message, uint16_t length) {
  // ...
});
```

**Comment by E3ton** [comment]
Great, thanks a lot!
