### ISSUE TITLE
Can not compile the example in Arduino UNO R4 WiFi board.

### ISSUE THREAD

**Issue by chongin** [skaarj1989/mWebSockets#65]
It show these errors:
Documents/Arduino/libraries/mWebSockets/src/base64/../platform.h:33:4: error: #error "Unsupported platform"
 #  error "Unsupported platform"

Documents/Arduino/libraries/mWebSockets/src/base64/Base64.cpp:9:12: fatal error: pgmspace.h: No such file or directory
 #  include <pgmspace.h>

**Comment by skaarj1989** [comment]
Try `master` branch.

**Comment by chongin** [comment]
> 

Yes, I downloaded the library from Arduino manager before, so it compiled failed. After I used the newest code from GitHub, it works now. Thank you.
