### ISSUE TITLE
support wss client question

### ISSUE THREAD

**Issue by maksvorobev** [skaarj1989/mWebSockets#66]
Hi ! I used this lib on stm32f411 black pill with default example. I receive only TCP and HTTP packets on my wensocket python server ( checking it with wireshark ) . Can I use wss client with TLS ?

**Comment by skaarj1989** [comment]
Sorry, `wss` is not supported.

**Comment by maksvorobev** [comment]
Thank for answer ! It looks like there is no library that supports wss and stm32f411 and arduino lib (
